# Generated by Django 5.2.5 on 2025-08-25 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('Admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('Certificate_id', models.AutoField(primary_key=True, serialize=False)),
                ('CV_id', models.IntegerField()),
                ('Certificate_Name', models.CharField(max_length=100)),
                ('Organization', models.CharField(max_length=100)),
                ('Year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CVtable',
            fields=[
                ('CV_id', models.AutoField(primary_key=True, serialize=False)),
                ('CV_Name', models.CharField(max_length=100)),
                ('Template_id', models.IntegerField()),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('Eduaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('CV_id', models.IntegerField()),
                ('Degree', models.CharField(max_length=100)),
                ('University', models.CharField(max_length=100)),
                ('Start_year', models.IntegerField()),
                ('End_year', models.IntegerField()),
                ('Description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('Experience_id', models.AutoField(primary_key=True, serialize=False)),
                ('CV_id', models.IntegerField()),
                ('Company_Name', models.CharField(max_length=100)),
                ('Start_date', models.DateTimeField(auto_now_add=True)),
                ('End_date', models.DateTimeField(auto_now_add=True)),
                ('Description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('Interest_id', models.AutoField(primary_key=True, serialize=False)),
                ('CV_id', models.IntegerField()),
                ('Interest_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('Language_id', models.AutoField(primary_key=True, serialize=False)),
                ('Language_Name', models.CharField(max_length=100)),
                ('Proficiency', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('Project_id', models.AutoField(primary_key=True, serialize=False)),
                ('CV_id', models.IntegerField()),
                ('Project_Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('Link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('Reference_id', models.AutoField(primary_key=True, serialize=False)),
                ('CV_id', models.IntegerField()),
                ('Reference_Name', models.CharField(max_length=100)),
                ('Designation', models.CharField(max_length=100)),
                ('Comapany', models.CharField(max_length=100)),
                ('Contact', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('Skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('CV_id', models.IntegerField()),
                ('Skill_Name', models.CharField(max_length=100)),
                ('Proficiency_level', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('Template_id', models.AutoField(primary_key=True, serialize=False)),
                ('Template_Name', models.CharField(max_length=100)),
                ('Preview_image', models.ImageField(upload_to='user_images/')),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('User_id', models.AutoField(primary_key=True, serialize=False)),
                ('Full_Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Personal_Details',
            fields=[
                ('Info_id', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Contact', models.IntegerField()),
                ('Address', models.CharField(max_length=500)),
                ('linked_in', models.CharField(max_length=100)),
                ('github', models.CharField(max_length=100)),
                ('CV_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvapp.cvtable')),
            ],
        ),
        migrations.AddField(
            model_name='cvtable',
            name='User_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvapp.user'),
        ),
    ]
