# Generated by Django 5.2.5 on 2025-08-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='CV_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='template',
            name='Preview_image',
            field=models.ImageField(upload_to='preview_images/'),
        ),
    ]
