# Generated by Django 5.2.5 on 2025-08-29 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0002_language_cv_id_alter_template_preview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='CV_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvapp.cvtable'),
        ),
        migrations.AlterField(
            model_name='education',
            name='CV_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvapp.cvtable'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='CV_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvapp.cvtable'),
        ),
        migrations.AlterField(
            model_name='interest',
            name='CV_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvapp.cvtable'),
        ),
        migrations.AlterField(
            model_name='language',
            name='CV_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvapp.cvtable'),
        ),
        migrations.AlterField(
            model_name='project',
            name='CV_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvapp.cvtable'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='CV_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvapp.cvtable'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='CV_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvapp.cvtable'),
        ),
    ]
