# Generated by Django 5.2.5 on 2025-08-29 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0003_alter_certificate_cv_id_alter_education_cv_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvtable',
            name='Template_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvapp.template'),
        ),
    ]
