# Generated by Django 5.2.5 on 2025-09-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0004_alter_cvtable_template_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_details',
            name='Profile_Image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
