# Generated by Django 5.2.5 on 2025-09-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0005_personal_details_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='Eduaction_id',
            new_name='Education_id',
        ),
        migrations.RenameField(
            model_name='reference',
            old_name='Comapany',
            new_name='Company',
        ),
        migrations.AddField(
            model_name='personal_details',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cvtable',
            name='Updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='Description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='End_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='Description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='End_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='Start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='language',
            name='Proficiency',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Conversational', 'Conversational'), ('Fluent', 'Fluent'), ('Native', 'Native')], max_length=50),
        ),
        migrations.AlterField(
            model_name='personal_details',
            name='Contact',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='personal_details',
            name='Email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personal_details',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personal_details',
            name='linked_in',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='Contact',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reference',
            name='Email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='Proficiency_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], max_length=50),
        ),
    ]
